import { Pool } from 'pg';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

const databaseUrl = process.env.DATABASE_URL ? new URL(process.env.DATABASE_URL) : null;
databaseUrl?.searchParams.delete('sslmode');
const pool = new Pool({ connectionString: databaseUrl?.toString(), ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false });
const secret = process.env.JWT_SECRET || 'change-this-secret-in-vercel';
const branch = process.env.BRANCH_NAME || 'Condong Catur';

const send = (res, status, body) => res.status(status).json(body);
const body = req => typeof req.body === 'string' ? JSON.parse(req.body || '{}') : (req.body || {});
const userFrom = req => { try { return jwt.verify(req.cookies?.absen_token || '', secret); } catch { return null; } };
const auth = (req, res, role) => { const user = userFrom(req); if (!user) { send(res, 401, { ok: false, message: 'Sesi login habis, silakan login ulang.' }); return null; } if (role && user.role !== role) { send(res, 403, { ok: false, message: 'Akses tidak diizinkan.' }); return null; } return user; };
const durationText = minutes => { const h = Math.floor(minutes / 60); const m = minutes % 60; return h ? `${h} Jam${m ? ` ${m} Menit` : ''}` : `${m} Menit`; };

async function init() {
  await pool.query(`CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, member_no VARCHAR(20) UNIQUE, name VARCHAR(150) NOT NULL, username VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'member', gender VARCHAR(20), status VARCHAR(20) NOT NULL DEFAULT 'Aktif', branch VARCHAR(100) DEFAULT 'Condong Catur', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS attendance_codes (id SERIAL PRIMARY KEY, code VARCHAR(20) NOT NULL, valid_date DATE NOT NULL, branch VARCHAR(100) DEFAULT 'Condong Catur', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS sessions (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, branch VARCHAR(100) DEFAULT 'Condong Catur', check_in TIMESTAMPTZ NOT NULL, check_out TIMESTAMPTZ, duration_minutes INTEGER, status VARCHAR(20) NOT NULL DEFAULT 'sedang_latihan', auto_checkout BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);
  const admin = await pool.query("SELECT id FROM users WHERE username = 'admin'");
  if (!admin.rowCount) await pool.query('INSERT INTO users (member_no,name,username,password,role) VALUES ($1,$2,$3,$4,$5)', ['ADMIN', 'Administrator', 'admin', await bcrypt.hash(process.env.ADMIN_PASSWORD || 'admin123', 10), 'admin']);
}
const ensureCode = async () => { const current = await pool.query('SELECT * FROM attendance_codes WHERE valid_date = CURRENT_DATE AND branch = $1 ORDER BY id DESC LIMIT 1', [branch]); if (current.rowCount) return current.rows[0]; const code = [...cryptoRandom()].join('').slice(0, 6); const result = await pool.query('INSERT INTO attendance_codes (code, valid_date, branch) VALUES ($1,CURRENT_DATE,$2) RETURNING *', [code, branch]); return result.rows[0]; };
const cryptoRandom = () => Array.from({ length: 8 }, () => Math.floor(Math.random() * 16).toString(16).toUpperCase());
const cleanSessions = async () => pool.query("UPDATE sessions SET check_out = check_in + INTERVAL '150 minutes', duration_minutes = 150, status = 'selesai', auto_checkout = TRUE WHERE status = 'sedang_latihan' AND check_in::date < CURRENT_DATE");

export default async function handler(req, res) {
  try {
    await init();
    const requestUrl = new URL(req.url, 'http://localhost');
    const path = requestUrl.searchParams.get('path') || requestUrl.pathname.replace(/^\/api\/?/, '').replace(/\/index(?:\.js)?$/, '');
    const input = body(req);
    if (path === 'auth/login' && req.method === 'POST') {
      const result = await pool.query("SELECT * FROM users WHERE username = $1 AND status = 'Aktif'", [input.username]);
      if (!result.rowCount || !(await bcrypt.compare(input.password || '', result.rows[0].password))) return send(res, 401, { ok: false, message: 'Username atau password salah.' });
      const user = result.rows[0]; const token = jwt.sign({ id: user.id, role: user.role, name: user.name, username: user.username, member_no: user.member_no }, secret, { expiresIn: '7d' });
      res.setHeader('Set-Cookie', `absen_token=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`);
      return send(res, 200, { ok: true, user: { id: user.id, name: user.name, username: user.username, role: user.role, member_no: user.member_no } });
    }
    if (path === 'auth/me' && req.method === 'GET') { const user = auth(req, res); return user ? send(res, 200, { ok: true, user }) : null; }
    if (path === 'auth/logout' && req.method === 'POST') { res.setHeader('Set-Cookie', 'absen_token=; HttpOnly; Path=/; Max-Age=0; SameSite=Lax'); return send(res, 200, { ok: true }); }
    if (path === 'member/status' && req.method === 'GET') { const user = auth(req, res, 'member'); if (!user) return null; await cleanSessions(); const result = await pool.query("SELECT * FROM sessions WHERE user_id = $1 AND status = 'sedang_latihan' ORDER BY id DESC LIMIT 1", [user.id]); return send(res, 200, { ok: true, active: !!result.rowCount, session: result.rows[0] || null }); }
    if (path === 'member/checkin' && req.method === 'POST') { const user = auth(req, res, 'member'); if (!user) return null; const value = String(input.code || '').trim().toUpperCase(); if (!value) return send(res, 400, { ok: false, message: 'Kode presensi wajib diisi.' }); await cleanSessions(); const active = await pool.query("SELECT id FROM sessions WHERE user_id = $1 AND status = 'sedang_latihan'", [user.id]); if (active.rowCount) return send(res, 409, { ok: false, already_active: true, message: 'Kamu masih punya sesi presensi yang aktif.' }); const code = await pool.query('SELECT * FROM attendance_codes WHERE valid_date = CURRENT_DATE AND active = TRUE ORDER BY id DESC LIMIT 1'); if (!code.rowCount || code.rows[0].code.toUpperCase() !== value) return send(res, 400, { ok: false, message: 'Kode presensi tidak valid atau sudah kedaluwarsa.' }); const result = await pool.query("INSERT INTO sessions (user_id,branch,check_in) VALUES ($1,$2,NOW()) RETURNING *", [user.id, code.rows[0].branch]); return send(res, 200, { ok: true, message: 'Check-in berhasil, selamat bekerja!', session: result.rows[0] }); }
    if (path === 'member/checkout' && req.method === 'POST') { const user = auth(req, res, 'member'); if (!user) return null; const result = await pool.query("SELECT * FROM sessions WHERE user_id = $1 AND status = 'sedang_latihan' ORDER BY id DESC LIMIT 1", [user.id]); if (!result.rowCount) return send(res, 400, { ok: false, message: 'Tidak ada sesi aktif.' }); const session = result.rows[0]; const minutes = Math.max(1, Math.ceil((Date.now() - new Date(session.check_in).getTime()) / 60000)); await pool.query("UPDATE sessions SET check_out = NOW(), duration_minutes = $1, status = 'selesai' WHERE id = $2", [minutes, session.id]); return send(res, 200, { ok: true, message: 'Sesi presensi berhasil diakhiri.', duration_minutes: minutes, duration_text: durationText(minutes) }); }
    if (path === 'member/history' && req.method === 'GET') { const user = auth(req, res, 'member'); if (!user) return null; const result = await pool.query("SELECT id,branch,TO_CHAR(check_in AT TIME ZONE 'Asia/Jakarta','DD Mon YYYY') date,TO_CHAR(check_in AT TIME ZONE 'Asia/Jakarta','HH24:MI') check_in,TO_CHAR(check_out AT TIME ZONE 'Asia/Jakarta','HH24:MI') check_out,status,duration_minutes,auto_checkout FROM sessions WHERE user_id = $1 ORDER BY check_in DESC LIMIT 100", [user.id]); return send(res, 200, { ok: true, total_hadir: result.rowCount, history: result.rows.map(row => ({ ...row, duration_text: row.duration_minutes ? durationText(row.duration_minutes) : null })) }); }
    if (path === 'admin/code') { const user = auth(req, res, 'admin'); if (!user) return null; if (req.method === 'POST') { if (input.action === 'regenerate') await pool.query('INSERT INTO attendance_codes (code,valid_date,branch) VALUES ($1,CURRENT_DATE,$2)', [[...cryptoRandom()].join('').slice(0, 6), branch]); if (input.action === 'toggle') { const current = await ensureCode(); await pool.query('UPDATE attendance_codes SET active = NOT active WHERE id = $1', [current.id]); } } const current = await ensureCode(); return send(res, 200, { ok: true, code: current.code, active: current.active, branch: current.branch }); }
    if (path === 'admin/today' && req.method === 'GET') { const user = auth(req, res, 'admin'); if (!user) return null; const query = new URL(req.url, 'http://localhost').searchParams.get('q') || ''; const result = await pool.query("SELECT s.id session_id,u.member_no,u.name,TO_CHAR(s.check_in AT TIME ZONE 'Asia/Jakarta','HH24:MI') check_in,TO_CHAR(s.check_out AT TIME ZONE 'Asia/Jakarta','HH24:MI') check_out,s.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.check_in::date=CURRENT_DATE AND u.name ILIKE $1 ORDER BY s.check_in DESC", [`%${query}%`]); return send(res, 200, { ok: true, total: result.rowCount, sedang_latihan: result.rows.filter(row => row.status === 'sedang_latihan').length, data: result.rows }); }
    if (path === 'admin/users' && req.method === 'GET') { const user = auth(req, res, 'admin'); if (!user) return null; const result = await pool.query("SELECT id,member_no,name,username,status,gender FROM users WHERE role='member' ORDER BY name"); return send(res, 200, { ok: true, data: result.rows }); }
    if (path === 'admin/users' && req.method === 'POST') { const user = auth(req, res, 'admin'); if (!user) return null; if (input.action === 'create') { const next = await pool.query("SELECT COALESCE(MAX(NULLIF(member_no, '')::INTEGER), 3346) + 1 member_no FROM users WHERE member_no ~ '^[0-9]+$'"); const result = await pool.query('INSERT INTO users (member_no,name,username,password,gender) VALUES ($1,$2,$3,$4,$5) RETURNING id,member_no,name,username,status,gender', [next.rows[0].member_no, input.name, input.username, await bcrypt.hash(input.password || 'member123', 10), input.gender || null]); return send(res, 200, { ok: true, user: result.rows[0] }); } if (input.action === 'toggle_status') { await pool.query("UPDATE users SET status = CASE WHEN status = 'Aktif' THEN 'Nonaktif' ELSE 'Aktif' END WHERE id = $1 AND role = 'member'", [input.id]); return send(res, 200, { ok: true }); } if (input.action === 'reset_password') { await pool.query('UPDATE users SET password = $1 WHERE id = $2 AND role = \'member\'', [await bcrypt.hash(input.password, 10), input.id]); return send(res, 200, { ok: true }); } if (input.action === 'delete') { await pool.query("DELETE FROM users WHERE id = $1 AND role = 'member'", [input.id]); return send(res, 200, { ok: true }); } }
    if (path === 'admin/manual' && req.method === 'POST') { const user = auth(req, res, 'admin'); if (!user) return null; const member = await pool.query("SELECT id,branch FROM users WHERE id = $1 AND role = 'member' AND status = 'Aktif'", [input.user_id]); if (!member.rowCount) return send(res, 404, { ok: false, message: 'Member aktif tidak ditemukan.' }); const active = await pool.query("SELECT id FROM sessions WHERE user_id = $1 AND status = 'sedang_latihan'", [input.user_id]); if (active.rowCount) return send(res, 409, { ok: false, message: 'Member masih memiliki sesi aktif.' }); await pool.query('INSERT INTO sessions (user_id,branch,check_in) VALUES ($1,$2,NOW())', [input.user_id, member.rows[0].branch || branch]); return send(res, 200, { ok: true, message: 'Presensi manual berhasil.' }); }
    if (path === 'admin/session' && req.method === 'POST') { const user = auth(req, res, 'admin'); if (!user) return null; if (input.action === 'checkout') { const session = await pool.query("SELECT * FROM sessions WHERE id = $1 AND status = 'sedang_latihan'", [input.session_id]); if (!session.rowCount) return send(res, 404, { ok: false, message: 'Sesi aktif tidak ditemukan.' }); const minutes = Math.max(1, Math.ceil((Date.now() - new Date(session.rows[0].check_in).getTime()) / 60000)); await pool.query("UPDATE sessions SET check_out = NOW(), duration_minutes = $1, status = 'selesai' WHERE id = $2", [minutes, input.session_id]); return send(res, 200, { ok: true, duration_text: durationText(minutes) }); } if (input.action === 'delete') { await pool.query('DELETE FROM sessions WHERE id = $1', [input.session_id]); return send(res, 200, { ok: true }); } }
    return send(res, 404, { ok: false, message: 'Endpoint tidak ditemukan.' });
  } catch (error) { console.error(error); return send(res, 500, { ok: false, message: 'Kesalahan server. Periksa DATABASE_URL PostgreSQL.' }); }
}
